[tool.poetry]
name = "oop-testing"
version = "0.1.0"
description = ""
authors = ["DavidMbiroMungai <DavidMbiroMungai@JITU-MP2EJHRW>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
